---
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install yamllint==1.19.0
  pre_build:
    commands:
      - yamllint cloudformation.yml .yamllint .s8/*.yml

artifacts:
  files:
    - cloudformation.yml
